name: flutter_pangrowth
description: flutter_pangrowth是一个可以帮助开发者直接引入穿山甲内容输出的插件。
version: 1.0.9+2
homepage: https://github.com/gstory0404/flutter_pangrowth
# 私有pub仓库地址
publish_to: https://pub.exiaokang.cn

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.flutter_pangrowth
        pluginClass: FlutterPangrowthPlugin
      ios:
        pluginClass: FlutterPangrowthPlugin
